spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: temperature-measurement
  data:
    redis:
      port: 6379

anomaly:
  detector:
    strategy: average

kafka:
  bootstrap-servers: localhost:9092
