spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: temperature-measurements
  data:
    redis:
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres

anomaly:
  detector:
    strategy: average
    average:
      min:
        amount: 10
    calculator:
      scale: 2
      threshold: 5.00

kafka:
  bootstrap-servers: localhost:9092